CREATE TABLE IF NOT EXISTS transactions.t_income(
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    c_amount NUMERIC(19,2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id INTEGER NOT NULL REFERENCES users.t_user(id)
);